export { default as AdminDashboard } from './authorized/Admin';
export { default as Dashboard } from './authorized/Dashboard';
export { default as History } from './authorized/History';
export { default as Settings } from './authorized/Settings';
export { default as Login } from './unauthorized/Login';
export { default as PageNotFound } from './unauthorized/PageNotFound';
export { default as PasswordRecovery } from './unauthorized/PasswordRecovery';
export { default as UpdatePassword } from './unauthorized/PasswordRecovery/UpdatePassword';
export { default as Registration } from './unauthorized/Registration';
