name: 'Chromatic'
on:
  push:
    paths:
      - 'packages/client/**'

defaults:
  run:
    working-directory: packages/client

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Install dependencies'
        run: yarn

      # 👇 Checks if the branch is not main and runs Chromatic
      - name: 'Publish to Chromatic'
        if: github.ref != 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true

      # 👇 Checks if the branch is main and accepts all changes in Chromatic
      - name: 'Publish to Chromatic and auto accept changes'
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
          exitZeroOnChanges: true
