name: 'Chromatic'
on:
  push:
    paths:
      - 'packages/client/**'

jobs:
  chromatic-deployment:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Install dependencies'
        run: yarn

      - name: 'Run client unit tests'
        working-directory: packages/client
        run: yarn test

      - name: 'Publish to Chromatic'
        uses: chromaui/action@v1
        with:
          workingDir: packages/client
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
